FEATURE_NAMES = [
    "event_count",
    "network_event_count",
    "dns_query_count",
    "max_dns_entropy",
    "avg_dns_entropy",
    "flow_duration",
    "packet_rate",
    "connection_count",
    "bytes_sent",
    "bytes_recv",
    "packets_sent",
    "packets_recv",
    "unique_remote_ips",
    "public_remote_ips",
    "listening_ports",
    "top_remote_port_count",
    "failed_connection_ratio",
    "tcp_flag_score",
    "beacon_interval_score",
    "outbound_frequency",
    "cpu_percent",
    "process_count",
]

MODEL_LAYERS = [
    "Random Forest fast screen",
    "XGBoost known-threat classifier",
    "Isolation Forest unknown-threat verifier",
    "Threat confidence voting layer",
]
