"""normalize_schemas_and_indexes

Revision ID: 8cdf24fcb8b8
Revises: a1a1deb8921a
Create Date: 2026-06-26 22:39:14.354619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdf24fcb8b8'
down_revision: Union[str, None] = 'a1a1deb8921a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_devices_risk_score'), 'devices', ['risk_score'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_index(op.f('ix_network_flows_end_time'), 'network_flows', ['end_time'], unique=False)
    op.create_index(op.f('ix_network_flows_start_time'), 'network_flows', ['start_time'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_system_logs_module'), 'system_logs', ['module'], unique=False)
    op.create_index(op.f('ix_traffic_logs_timestamp'), 'traffic_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_logs_timestamp'), table_name='traffic_logs')
    op.drop_index(op.f('ix_system_logs_module'), table_name='system_logs')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_network_flows_start_time'), table_name='network_flows')
    op.drop_index(op.f('ix_network_flows_end_time'), table_name='network_flows')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_risk_score'), table_name='devices')
    # ### end Alembic commands ###
