"""add_enterprise_auth_tables

Revision ID: e2b77cee1b0b
Revises: 2984920c812d
Create Date: 2026-07-05 23:53:06.667164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b77cee1b0b'
down_revision: Union[str, None] = '2984920c812d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_audits',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_audits_user_id'), 'login_audits', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_password_histories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_password_histories_user_id'), 'user_password_histories', ['user_id'], unique=False)
    op.add_column('alerts', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    if not is_sqlite:
        op.alter_column('alerts', 'device_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        op.alter_column('alerts', 'prediction_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=True)
        op.alter_column('alerts', 'assigned_to',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=True)
        op.alter_column('alerts', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
    op.create_index(op.f('ix_alerts_is_deleted'), 'alerts', ['is_deleted'], unique=False)
    
    if not is_sqlite:
        op.alter_column('audit_logs', 'user_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=True)
        op.alter_column('audit_logs', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        op.alter_column('botnet_families', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
    op.add_column('devices', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    
    if not is_sqlite:
        op.alter_column('devices', 'registered_by',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=True)
        op.alter_column('devices', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
    op.create_index(op.f('ix_devices_is_deleted'), 'devices', ['is_deleted'], unique=False)
    
    if not is_sqlite:
        op.alter_column('ml_predictions', 'device_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        op.alter_column('ml_predictions', 'flow_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=True)
        op.alter_column('ml_predictions', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        op.alter_column('network_flows', 'device_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        op.alter_column('network_flows', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        op.alter_column('reports', 'generated_by',
                   existing_type=sa.UUID() if hasattr(sa, 'UUID') else sa.String(),
                   existing_nullable=True)
        op.alter_column('reports', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        op.alter_column('system_logs', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        op.alter_column('threat_intelligence', 'botnet_family_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=True)
        op.alter_column('threat_intelligence', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        op.alter_column('traffic_logs', 'device_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        op.alter_column('traffic_logs', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True))
    
    if not is_sqlite:
        op.alter_column('users', 'role',
                   existing_type=sa.VARCHAR(length=16),
                   type_=sa.Enum('super_admin', 'soc_manager', 'soc_analyst', 'incident_responder', 'read_only', 'security_analyst', 'viewer', name='user_role'),
                   existing_nullable=False)
        op.alter_column('users', 'id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_admin', 'soc_manager', 'soc_analyst', 'incident_responder', 'read_only', 'security_analyst', 'viewer', name='user_role'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('users', 'last_password_change')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'department')
    op.drop_column('users', 'full_name')
    op.alter_column('traffic_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('traffic_logs', 'device_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('threat_intelligence', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('threat_intelligence', 'botnet_family_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('system_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reports', 'generated_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('network_flows', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('network_flows', 'device_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('ml_predictions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('ml_predictions', 'flow_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('ml_predictions', 'device_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_devices_is_deleted'), table_name='devices')
    op.alter_column('devices', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('devices', 'registered_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('devices', 'is_deleted')
    op.alter_column('botnet_families', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_index(op.f('ix_alerts_is_deleted'), table_name='alerts')
    op.alter_column('alerts', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('alerts', 'assigned_to',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('alerts', 'prediction_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('alerts', 'device_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('alerts', 'is_deleted')
    op.drop_index(op.f('ix_user_password_histories_user_id'), table_name='user_password_histories')
    op.drop_table('user_password_histories')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_login_audits_user_id'), table_name='login_audits')
    op.drop_table('login_audits')
    # ### end Alembic commands ###
